name: C++ Build CI

on:
  push:
    branches: [ main, feature_chat_server ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y g++

    - name: Build project using script
      run: |
        chmod +x scripts/build.sh
        ./scripts/build.sh

    - name: Run basic check
      run: echo "Build successful"